### ISSUE TITLE
Device inverter instead of pvinverter possible?

### ISSUE THREAD

**Issue by TheGrumpyBadger** [henne49/dbus-opendtu#42] opened 2023-03-05 19:49 UTC
My HM-350 is connected to a LFP battery, which is charged by a Victron MPPT.
Is it possible to show the HM-350 as an inverter, as it is using DC power instead of PV ?

**Comment by henne49** [comment] 2023-03-06 21:37
as long as you have a DTU like ahoy or opendtu, that we can read data from, it can be displayed in venus OS

**Comment by ude6** [comment] 2023-03-09 19:59
Hi,
I agree. I am currently using your code to display the inverter (connected to the battery) as
a PV-Inverter. It runs very well. BUT it assumes the energy comes from PV where in reality it comes from the battery.

So when the inverter runs I see for example:

Battery (via dbus-serialbattery) -600w
PV-Inverter ( via your dbus-opendtu) +600w
DC-Power (calculated by victron) +600w 

The problem is that the cerbo is not netting the DC-Power (which is the input to the inverter) 
with the PV-Inverter.

So the question is: Can the Opendtu (or Ahoy) be used as an inverter that is powered by DC load?
![image](https://user-images.githubusercontent.com/4454147/224140258-6ceb258a-f2c1-4de8-890e-a05b24e1b19d.png)

Thanks

Andreas

**Comment by ude6** [comment] 2023-03-09 20:07
Yes, I would assume that something like this would be through the com.victronenergy.vebus.
It would need to look like a Multiplus to the Cerbo (I guess)....

**Comment by henne49** [comment] 2023-03-09 20:12
I planned something for shelly https://github.com/henne49/dbus-opendtu/issues/32, but it was not working. This requires some rework, give it a try and you can submit a PR to include into the code. But wait until we Merged https://github.com/henne49/dbus-opendtu/pull/43

**Comment by ude6** [comment] 2023-03-09 20:13
Sounds great!

**Comment by ude6** [comment] 2023-03-09 23:17
This looks close: https://github.com/Telekatz/venus.dbus-hoymiles

**Comment by henne49** [comment] 2023-03-10 08:28
we did a merge, your link is a different use case. Maybe that project is a better bit for your use case

**Comment by ude6** [comment] 2023-03-10 09:26
I will try to ask the autor there for a possible update to disble the steering of the HM input.

**Comment by Head** [comment] 2023-03-14 17:24
Was just reading the code and then found this _issue_.
This project simulates the opendtu as a pvinverter: https://github.com/victronenergy/venus/wiki/dbus#pv-inverters
_We_ would need an inverter: https://github.com/victronenergy/venus/wiki/dbus#inverter

It shouldn't be that hard to take this code and change `com.victronenergy.pvinverter` to `com.victronenergy.inverter` and also change the paths in the update funtion https://github.com/henne49/dbus-opendtu/blob/main/dbus-opendtu.py#L423 to match the ones required by the inverter interface. But maybe that should ne another project/fork of this one... Or maybe a config flag?

**Comment by henne49** [comment] 2023-03-15 11:09
I think it needs to be a config flag, which allows for different mode. If you are interested, please create a fork and test, we can help with the code and Pull Request. We would include this into code for sure, just have no time yet to do it myself.

**Comment by dsteinkopf** [comment] 2023-03-25 08:05
Maybe, the change #53 (based on feature request #52) will also help in this case. I will be able to configure servicename `com.victronenergy.inverter`.

**Comment by dsteinkopf** [comment] 2023-03-25 14:16
Closing thing because of #53. Please reopen or create a new issue if necessary.

**Comment by henne49** [comment] 2023-03-26 05:34
Reopening, as we need to also implement it for ahoy and opendtu and not just template

**Comment by TheGrumpyBadger** [comment] 2023-03-28 16:17
just tried it.
---
### Only needed for OpenDTU and ahoy
# AcPosition 0=AC input 1; 1=AC output; 2=AC output 2
# 1st inverter
[INVERTER0]
Phase=L1
DeviceInstance=34
AcPosition=0
Servicename=com.victronenergy.inverter

# 2nd inverter
[INVERTER1]
Phase=L1
DeviceInstance=35
AcPosition=0
Servicename=com.victronenergy.pvinverter
---
Inverter0 is not connected, Interverter1 works fine.

<img width="374" alt="Screenshot 2023-03-28 181654" src="https://user-images.githubusercontent.com/45455179/228304086-a7e35834-0a99-48bf-83ef-64723d638044.png">

**Comment by TheGrumpyBadger** [comment] 2023-03-28 16:28
I think for inverter there are other variables:
https://github.com/victronenergy/venus/wiki/dbus#inverter

<img width="375" alt="Screenshot 2023-03-28 182636" src="https://user-images.githubusercontent.com/45455179/228306527-35b3e31e-41c0-47fd-bcc0-c3c70c8a8286.png">

**Comment by TheGrumpyBadger** [comment] 2023-04-02 09:50
I think we will need:

`/Dc/0/Voltage             <- Battery voltage
/Ac/Out/L1/V              <- AC Output voltage
/Ac/Out/L1/I              <- AC Output current
/Ac/Out/L1/P              <- Not used on vedirect inverters 
/State                    <- 0=Off; 1=Low Power; 2=Fault; 9=Inverting`

**Comment by Tom051276** [comment] 2023-04-27 05:50
Dear all, was this feature request from @TheGrumpyBadger already built in ? I tried to use the Servicename=com.victronenergy.inverter for Inverter0 But without luck. Seems it is not yet implemented...

**Comment by dsteinkopf** [comment] 2023-04-27 06:41
Yes, setting the servicename was implemented in #53. But it seems there are devices (servicenames) where it is not sufficient to only set the servicename and some more attributes need to be set. This is why THIS ticket ist still open.

**Comment by 0x7878** [comment] 2023-04-27 06:44
Hey @Tom051276 would you mind to post the debug log? 

Logging=DEBUG


Right now it looks correct for me. 

```python
if dtuvariant != constants.DTUVARIANT_TEMPLATE:
            logging.info("Registering dtu devices")
            servicename=get_config_value(config, "Servicename", "INVERTER", 0, "com.victronenergy.pvinverter")
            service = DbusService(
                servicename=servicename,
                paths=paths,
                actual_inverter=0,
            )
```

Maybe there's something wrong with the getter. I'm not able to debug that right now.

**Comment by TheGrumpyBadger** [comment] 2023-04-27 07:29
As far as I see the paths are only implemented for pv inverter:
`        paths = {
            "/Ac/Energy/Forward": {
                "initial": None,
                "textformat": _kwh,
            },  # energy produced by pv inverter
            "/Ac/Power": {"initial": None, "textformat": _w},
            "/Ac/L1/Voltage": {"initial": None, "textformat": _v},
            "/Ac/L2/Voltage": {"initial": None, "textformat": _v},
            "/Ac/L3/Voltage": {"initial": None, "textformat": _v},
            "/Ac/L1/Current": {"initial": None, "textformat": _a},
            "/Ac/L2/Current": {"initial": None, "textformat": _a},
            "/Ac/L3/Current": {"initial": None, "textformat": _a},
            "/Ac/L1/Power": {"initial": None, "textformat": _w},
            "/Ac/L2/Power": {"initial": None, "textformat": _w},
            "/Ac/L3/Power": {"initial": None, "textformat": _w},
            "/Ac/L1/Energy/Forward": {"initial": None, "textformat": _kwh},
            "/Ac/L2/Energy/Forward": {"initial": None, "textformat": _kwh},
            "/Ac/L3/Energy/Forward": {"initial": None, "textformat": _kwh},
        }`

The paths for a "non-pv"-inverter I posted above.

**Comment by 0x7878** [comment] 2023-04-27 12:07
Got you. I created a new branch [feature-non-pv-inverter](/henne49/dbus-opendtu/tree/feature-non-pv-inverter). I'm not able to test it yet but maybe it's a start

**Comment by TheGrumpyBadger** [comment] 2023-04-27 14:02
Yes, I got values:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/45455179/234886012-1de8bc09-e2d2-4c95-80e2-ee07c044a06a.png">

But no visual:
<img width="601" alt="image" src="https://user-images.githubusercontent.com/45455179/234886177-217c8564-ecb0-49f5-95cc-a8768ca19b08.png">

**Comment by TheGrumpyBadger** [comment] 2023-04-27 14:05
2023-04-27 14:04:38,184 root DEBUG calling http://192.168.178.200/api/livedata/status with timeout=2.5
2023-04-27 14:04:38,191 urllib3.connectionpool DEBUG Starting new HTTP connection (1): 192.168.178.200:80
2023-04-27 14:04:38,261 urllib3.connectionpool DEBUG http://192.168.178.200:80 "GET /api/livedata/status HTTP/1.1" 200 1401
2023-04-27 14:04:38,265 root DEBUG function fetch_url finished in 81 ms
2023-04-27 14:04:40,972 root DEBUG _get_value_handler called for /
2023-04-27 14:04:40,973 root DEBUG {'Mgmt/ProcessName': dbus.String('/data/dbus-opendtu/dbus_service.py', variant_level=1), 'Mgmt/ProcessVersion': dbus.String('Unkown version, and running on Python 3.8.13', variant_level=1), 'Mgmt/Connection': dbus.String('OpenDTU HTTP JSON service', variant_level=1), 'DeviceInstance': dbus.Int32(34, variant_level=1), 'ProductId': dbus.Int32(65535, variant_level=1), 'ProductName': dbus.String('OpenDTU', variant_level=1), 'CustomName': dbus.String('HM350-Akku', variant_level=1), 'Connected': dbus.Int32(1, variant_level=1), 'Latency': dbus.Array([], signature=dbus.Signature('i'), variant_level=1), 'FirmwareVersion': dbus.Double(0.1, variant_level=1), 'HardwareVersion': dbus.Int32(0, variant_level=1), 'Position': dbus.Int32(1, variant_level=1), 'Serial': dbus.String('112183215725', variant_level=1), 'UpdateIndex': dbus.Int32(0, variant_level=1), 'StatusCode': dbus.Int32(0, variant_level=1), 'Ac/Energy/Forward': dbus.Array([], signature=dbus.Signature('i'), variant_level=1), 'Ac/Power': dbus.Array([], signature=dbus.Signature('i'), variant_level=1), 'Ac/L1/Voltage': dbus.Array([], signature=dbus.Signature('i'), variant_level=1), 'Ac/L2/Voltage': dbus.Array([], signature=dbus.Signature('i'), variant_level=1), 'Ac/L3/Voltage': dbus.Array([], signature=dbus.Signature('i'), variant_level=1), 'Ac/L1/Current': dbus.Array([], signature=dbus.Signature('i'), variant_level=1), 'Ac/L2/Current': dbus.Array([], signature=dbus.Signature('i'), variant_level=1), 'Ac/L3/Current': dbus.Array([], signature=dbus.Signature('i'), variant_level=1), 'Ac/L1/Power': dbus.Array([], signature=dbus.Signature('i'), variant_level=1), 'Ac/L2/Power': dbus.Array([], signature=dbus.Signature('i'), variant_level=1), 'Ac/L3/Power': dbus.Array([], signature=dbus.Signature('i'), variant_level=1), 'Ac/L1/Energy/Forward': dbus.Array([], signature=dbus.Signature('i'), variant_level=1), 'Ac/L2/Energy/Forward': dbus.Array([], signature=dbus.Signature('i'), variant_level=1), 'Ac/L3/Energy/Forward': dbus.Array([], signature=dbus.Signature('i'), variant_level=1), 'Ac/Out/L1/I': dbus.Double(1.059999943, variant_level=1), 'Ac/Out/L1/V': dbus.Double(234.1000061, variant_level=1), 'Dc/0/Voltage': dbus.Int32(49, variant_level=1)}

**Comment by TheGrumpyBadger** [comment] 2023-04-27 14:07
Perhaps the /state has to be 0 when I is 0 and 9 when I is > 0.
And /Mode to 2 when working.

**Comment by 0x7878** [comment] 2023-04-27 14:16
@dsteinkopf I have no idea how to contact you on Discord. Just add me there `Maurice#2144`

@TheGrumpyBadger I'll change/check this later. As I said I couldn't test it ;-)

**Comment by TheGrumpyBadger** [comment] 2023-04-27 16:14
`            "/Mode": {"initial": 2, "textformat": None},

            "/State": {"initial": 9, "textformat": None}
`

did it.

Line 87/77 in dbus-opendtu.py

<img width="366" alt="image" src="https://user-images.githubusercontent.com/45455179/234925264-4cfc3bb6-5212-41a5-95a5-5c947c43bf0c.png">

<img width="372" alt="image" src="https://user-images.githubusercontent.com/45455179/234925460-4936426f-4d98-4ca1-9dbe-01b26a9f0db2.png">

**Comment by 0x7878** [comment] 2023-04-27 17:36
Great job! 👍

**Comment by henne49** [comment] 2023-04-27 20:39
@0x7878 will you update the branch and create the PR? Well done guys

**Comment by Tom051276** [comment] 2023-04-28 05:17
@0x7878 @TheGrumpyBadger Awesome !!! I will give it a new try this weekend. Sounds great, Thank you for your work.

**Comment by ude6** [comment] 2023-04-29 13:11
Hi,
great progress and I am excited to use this.
When I tried the branch on a spare Rspi I found that for me the changes requested by @TheGrumpyBadger looked like they were not in the code?
For ref:
"        "/Mode": {"initial": 2, "textformat": None},
        "/State": {"initial": 9, "textformat": None}
did it.

Line 87/88 in dbus-opendtu.py"

Also the inverter is inverter no2 in my list and it did not get any values. (But that may be due to my hasty / maybe faulty setup of the raspi..

Thanks!

ude6

**Comment by TheGrumpyBadger** [comment] 2023-04-29 13:20
Hey ude6,

this two lines has to be added to the code, has to look like this:

            "/Ac/Out/L1/I": {"initial": None, "textformat": _a},
            "/Ac/Out/L1/V": {"initial": None, "textformat": _v},
            "/Ac/Out/L1/P": {"initial": None, "textformat": _w},
            "/Dc/0/Voltage": {"initial": None, "textformat": _v},
            "/Mode": {"initial": 2, "textformat": None},
            "/State": {"initial": 9, "textformat": None}
        }

**Comment by TheGrumpyBadger** [comment] 2023-04-29 13:24
@henne49 : I created a pull request for this to lines.

**Comment by 0x7878** [comment] 2023-04-29 20:00
This is not necessary as I am still working on it. Dbus_opendtu.py isn't really the best place to put the code either. In this section are some functions with some callbacks on text format.

The last commit broke some things that I already fixed but didn't push. I hope I'll be done with that tomorrow. I will also check why you might not be getting the values.

**Comment by Tom051276** [comment] 2023-05-01 17:39
@TheGrumpyBadger Is The total consumption calculated correct? I am wondering that now only the net in is summed up, but not the ac-out delivered from the hoymiles…
Before these change the hoymiles deliver was summed up in PV Power in, which was also not correct… Not sure how to solve this… I do not have the DC module like you have…

**Comment by Tom051276** [comment] 2023-05-01 17:44
![16829630109473798068355189133440](https://user-images.githubusercontent.com/73222689/235499488-5f3513b4-c0c7-4bb5-8a07-4545f66c6610.jpg)

**Comment by TheGrumpyBadger** [comment] 2023-05-01 17:50
This look good on my side:
<img width="363" alt="image" src="https://user-images.githubusercontent.com/45455179/235500267-1d97997f-187c-45d8-834f-8aa2599c4166.png">

in VRM it look not fine, but its ok for me:
<img width="905" alt="image" src="https://user-images.githubusercontent.com/45455179/235500367-81be1f79-e3a7-4faa-a66c-3a4332292681.png">

**Comment by Tom051276** [comment] 2023-05-01 18:03
@TheGrumpyBadger Ah okay, then you have the same problem on vrm site like I have. Any ideas how to solve this miscalculation on vrm?
Would be great if vrm site an also be fixed...

**Comment by TheGrumpyBadger** [comment] 2023-05-02 07:19
As far as I see there are no Victron inverters that can synchronize with die grid.
So the usecase we have is not supported in VRM. It is not possible to add grid and inverter power in the charts.

**Comment by TheGrumpyBadger** [comment] 2023-05-04 07:31
I found some miscalculations in VRM with AcPosition=1.
Doing some more testing, but AcPosition=0 seems to be better for the inverter.

**Comment by 0x7878** [comment] 2023-05-04 08:08
Good to know. If so, such information belongs to the readme. I also figured out that (at least in my installation) it takes up to 10 minutes before the VRM-Portal starts showing the live values of an e.g. (PV-)inverter.

**Comment by henne49** [comment] 2023-05-04 08:17
The 10 minutes can be configured in vrm or Venus, as the graphs you see are historical, that is why you have a delay.

I would at least use a delay of 10 minutes, as too short delays, you can have historical errors in case of unreachable or reboot of opendtu when opendtu shows 0

**Comment by dsteinkopf** [comment] 2023-05-04 08:47
@henne49 ah yes, that's probably the rease for the delay. I am "happily" using 1 Minute.


> I found some miscalculations in VRM with AcPosition=1. Doing some more testing, but AcPosition=0 seems to be better for the inverter.

It's in the config.ini: `# 0=AC input 1; 1=AC output; 2=AC output 2`. Yes, it should also be in the readme. But it's no "soft decision", it's a fact that must be configured correctly (where is the inverter connected), isn't it?

**Comment by TheGrumpyBadger** [comment] 2023-05-04 11:06
looks good so far:
<img width="913" alt="image" src="https://user-images.githubusercontent.com/45455179/236186765-bb4cb127-780e-4760-aa24-ca9eb3c926b8.png">

<img width="657" alt="image" src="https://user-images.githubusercontent.com/45455179/236186825-b3c640bd-bc26-4fd6-bcb7-194dc01301b8.png">

**Comment by 0x7878** [comment] 2023-05-04 11:55
In general: If a device becomes an inverter, the device in the middle (with the Victron logo) represents that device. This is why there is a label "Inverting, Off, etc.".

Furthermore, it works like that: The inverter takes Energy from the Battery and pushes it to AC-Loads. which then shows up in "consumption".

Feel free to correct me if something that I said isn't right.

**Comment by TheGrumpyBadger** [comment] 2023-05-04 13:07
You are right. On the screenshot are two HM-350 on a single openDTU-onbattery.
The first one ist an L1 and the inverter, it is feeded by an 24V LFP battery,
second one is on L3 and is a normal pvinverter on L3.
Both are now on AcPosition=0 and the numbers seems to be right.

**Comment by TheGrumpyBadger** [comment] 2023-05-04 13:19
> It's in the config.ini: `# 0=AC input 1; 1=AC output; 2=AC output 2`. Yes, it should also be in the readme. But it's no "soft decision", it's a fact that must be configured correctly (where is the inverter connected), isn't it?

for the inverter config it's indeed a soft decision. An inverter has no "AC input", so I thought "AC output" must be right, but perhaps not. That's why I'm in testing.

**Closed** 2023-05-04 16:57 UTC
Labels: enhancement

**Comment by 0x7878** [comment] 2023-05-16 20:48
Hey 👋
Please remove the hash sign "#" otherwise it will work as default (in this case PV inverter). After that check the values on your cerbo or via the terminal. See the readme for useful commands

**Comment by DrknMonkey** [comment] 2023-05-17 20:32
Thank you... you mean it so or:

![config](https://github.com/henne49/dbus-opendtu/assets/127410287/ed1fdbb2-8386-4991-ac2b-eb48561b1fea)

Unfortunately in the Cerbo is the HM-300 Status then unknown:
![Cerbo](https://github.com/henne49/dbus-opendtu/assets/127410287/8649e523-96b3-4cf2-b842-b5ccb4967ca1)

**Comment by 0x7878** [comment] 2023-05-17 21:04
That's right. I'll try your setup with a test device the next days. It could be that an Inverter does not have ac in which lead to your problem. Could you try ac out?

**Comment by DrknMonkey** [comment] 2023-05-17 22:07
Not so easy... but i have activate the AC-IN from the Multiplus, unfortunately still the same.

**Comment by 0x7878** [comment] 2023-05-17 22:35
Ok I see. First of all this setup was implemented without a Multiplus in place. But still... I'm wondering why there are no values at all in your setup. I'll try to figure it out but because of "Vatertag" it has to wait ;-)

**Comment by DrknMonkey** [comment] 2023-05-17 23:48
Thank you... it would be nice if it works with a Multiplus too :). But first i wish you a great "Vatertag" ;).

**Comment by WilliDerTiger** [comment] 2023-05-21 10:58
Hello,
Thanks for the good integration into the Victron world ( Cerbo GX ).
I have a Shelly 3EM working on the grid, which I have successfully connected via [https://github.com/fabian-lauer/dbus-shelly-3em-smartmeter](url).
I have a Victron 150/35 MPPT pv-charger for my battery 48V.
From the battery, I feed a Hoymiles HM-800 into the L3 grid.
A second Hoymiles HM-600 (PV inverter) feeds PV directly to L3 in the grid ( 1st inverter ).
This has all been integrated correctly,
except that the HM-800 (inverter) feeds into L1 according to the display.

I have set it to L3 in config.ini ( 2nd inverter ).
<img width="793" alt="Bildschirmfoto 2023-05-21 um 12 14 46" src="https://github.com/henne49/dbus-opendtu/assets/124721361/6e054549-7b8f-4263-b1fd-dc2601a0f448">

How can I change it to L3?

<img width="543" alt="Bildschirmfoto 2023-05-21 um 12 16 44" src="https://github.com/henne49/dbus-opendtu/assets/124721361/36876c37-0f06-46ac-975d-064cbd46d62e">

<img width="793" alt="Bildschirmfoto 2023-05-21 um 12 12 55" src="https://github.com/henne49/dbus-opendtu/assets/124721361/9f58497d-c80f-4fa4-ad9a-d7dd0d1c07df">
<img width="545" alt="Bildschirmfoto 2023-05-21 um 12 12 15" src="https://github.com/henne49/dbus-opendtu/assets/124721361/661f9110-613f-4ff0-baba-5306644d4444">

<img width="545" alt="Bildschirmfoto 2023-05-21 um 12 12 33" src="https://github.com/henne49/dbus-opendtu/assets/124721361/fee72493-a783-4dc1-8c28-9ea1613a5424">

Thanks

**Comment by 0x7878** [comment] 2023-05-21 11:12
Victron doesn't support it. 
![Screenshot_20230521-130644](https://github.com/henne49/dbus-opendtu/assets/17197791/1e856bc5-7682-422c-b432-8e4039ed6b2d)
They have no other endpoint than L1 and I didn't test a different one because it would then be an undocumented endpoint.

**Comment by WilliDerTiger** [comment] 2023-05-21 11:17
OK, then I have to live with it.
Thanks

**Comment by dsteinkopf** [comment] 2023-05-21 11:43
We are currently (atm) doing several experiments, but yes, it seems Victron does not support it... At least not this way, maybe there is another one...

**Comment by TheGrumpyBadger** [comment] 2023-05-21 20:17
Please keep in mind Victron never intended to use an inverter on a system conncted with the grid.

**Comment by WilliDerTiger** [comment] 2023-05-22 15:23
Yes, will certainly be better,
to imitate Multiplus.

**Comment by dsteinkopf** [comment] 2023-05-22 16:10
What do you mean by mimic/imitate a Multiplus?

**Comment by DrknMonkey** [comment] 2023-05-27 09:17
> Ok I see. First of all this setup was implemented without a Multiplus in place. But still... I'm wondering why there are no values at all in your setup. I'll try to figure it out but because of "Vatertag" it has to wait ;-)

Hello,

gives it already a Solution or is it not possible :)

**Comment by 0x7878** [comment] 2023-05-27 14:45
We're still experimenting but it seems that it does not work as a an Inverter. I'll rebuild the code base to support more device's. I cannot tell when I start because I'm also busy right now. :-(

**Comment by muellcy** [comment] 2024-08-02 13:32
I have expanded my PV system and included a Cerbo-SGX. So far everything is working fine . There is just one thing that I don't see displaying correctly. The “total solar display value” always adds the power that the Hoymiles HM 1500 feeds in to the PV power that comes from the MPPT trackers. Normally this should be displayed as “AC Load”, which I get separately. The AC load values ​​are correct. I tried all possible options (AC-position 0-2 and Servicename = pvinverter, charger and inverter). The enclodes config the currently running correctly displays the at least AC loads.  
My PV system consists of 2 Victron mppt trackers, a Daly BMS with LifePo4 cells. 
Furthermore, a "Hoymiles HM1500" inverter and a "Shelly Pro 3EM" as well as the Cerbo-sgx.  
Does anyone have an idea how to solve the problem? 
I think it has to do with the "servicename" but I am not sure. As said I tried all 3 to me known servicenames. No one made a difference, nor was solving the issue.
<img width="459" alt="2024-08-02 15_26_20-192 168 1 110 - PuTTY" src="https://github.com/user-attachments/assets/29acb9e2-4134-4008-8628-e49fb1adcb92">

**Comment by 0x7878** [comment] 2024-08-02 20:56
If I got you right, you want to tell victron that your hoymiles is actually an ac-inverter rather than an pv-inverter. If I remember right there is currently no solution for this use case. I'd like to emulate a Multiplus for this situation but I think there is much more that has to be implemented. 

Just a note: In your config you did not comment out the service name. So it won't work like this. Feel free to try some other variations but I'm not sure if it works.

**Comment by muellcy** [comment] 2024-08-04 08:58
Yes, that is exactly what I try to achive I do not have an victron inverter in my installation. Only the Hoymiles HM1500 which is running as an ac-inverter. I found an emulation for victron multiplus inverters. But this implementaion was also not solving the problem. It is a shame that there is not solution available.  Anyhow thanks for your clarification on this issue :-(
